# Changes here will be overwritten by Copier.
_commit: 1.11.2
_src_path: gh:pawamoy/copier-uv
author_email: hectorespertpardo@gmail.com
author_fullname: Hector Espert
author_username: hectorespert
copyright_date: '2025'
copyright_holder: Timothée Mazzucotelli
copyright_holder_email: dev@pawamoy.fr
copyright_license: ISC
project_description: MkDocs plugin to publish documentation to ClickUp Pages.
project_name: mkdocs-clickup
python_package_command_line_name: ''
python_package_distribution_name: mkdocs-clickup
python_package_import_name: mkdocs_clickup
repository_name: mkdocs-clickup
repository_namespace: hectorespert
repository_provider: github.com

